### PR TITLE
Update to latest commit

### PR DESCRIPTION
**Pull request by php1ic**
The qt-color-widgets packages has had new commits. Update this repo to use the newest commit.

### CODE REVIEW

**Comment by php1ic** [comment]
Hi @zjttoefs, @amues, @martukas,

Sorry for the spam, but is one of you able to review this PR?

Thanks

**Comment by zjttoefs** [comment]
Not Spam. Thanks for the nudge!

**Comment by php1ic** [comment]
Can someone please re-run the Jenkins pipeline. I'm having problems using the latest version and I think the failed CentOS upload may be the issue.

**Comment by amues** [comment]
@php1ic I've re-run the Jenkins job and the package has been re-uploaded.

**Pull request merged**
